<?php

require_once '../AttributeInfo.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 14:52:25.
 */
class AttributeInfoTest extends PHPUnit_Framework_TestCase {

    /**
     * @covers AttributeInfo::__construct
     * @expectedException Exception
     */
    public function testConstructorWithEmptyAttribute() {
        $att = new AttributeInfo("","");
    }
    
    /**
     * @covers AttributeInfo::__construct
     */
    public function testConstructorValidStringValues() {
        $att = new AttributeInfo("test","value");
    }
    
    /**
     * @covers AttributeInfo::__construct
     */
public function testConstructorValidArrayValues() {
        $values = ["1","2"];
        $att = new AttributeInfo("test",$values);
    }
    
    /**
     * @covers AttributeInfo::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        $att = new AttributeInfo("test","value");
        $this->assertEquals("test",$att->getName());
    }

    /**
     * @covers AttributeInfo::getValues
     * @todo   Implement testGetValues().
     */
    public function testGetValues() {
        $values = ["1","2"];
        $att = new AttributeInfo("test",$values);
        $this->assertEquals($values,$att->getValues());
    }

}
