<?php

require_once '../AttributeList.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 14:57:34.
 */
class AttributeListTest extends PHPUnit_Framework_TestCase {

    /**
     * @covers AttributeList::__construct
     * @covers AttributeList::getAttributeInfo
     */
    public function testGetAttributeInfo() {
        $list = new AttributeList();
        $this->assertTrue(is_a($list->getAttributeInfo('rel'), 'AttributeInfo'));
    }

    /**
     * @covers AttributeList::__construct
     * @covers AttributeList::getAttributeInfo
     */
    public function testGetAttributeEmpty() {
        $list = new AttributeList();
        $this->assertFalse($list->getAttributeInfo(''));
    }
}
