<?php

include('../Parser.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-07 at 12:32:50.
 */
class JNodeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JNode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JNode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers JNode::setCloseTagFound
     * @todo   Implement testSetCloseTagFound().
     */
    public function testSetCloseTagFound() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getCloseTagFound
     * @todo   Implement testGetCloseTagFound().
     */
    public function testGetCloseTagFound() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setCloseTagLn
     * @todo   Implement testSetCloseTagLn().
     */
    public function testSetCloseTagLn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getCloseTagLn
     * @todo   Implement testGetCloseTagLn().
     */
    public function testGetCloseTagLn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setCloseTagInd
     * @todo   Implement testSetCloseTagInd().
     */
    public function testSetCloseTagInd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getCloseTagInd
     * @todo   Implement testGetCloseTagInd().
     */
    public function testGetCloseTagInd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::addError
     * @todo   Implement testAddError().
     */
    public function testAddError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setUid
     * @todo   Implement testSetUid().
     */
    public function testSetUid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getAttr
     * @todo   Implement testGetAttr().
     */
    public function testGetAttr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::addAttr
     * @todo   Implement testAddAttr().
     */
    public function testAddAttr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getUid
     * @todo   Implement testGetUid().
     */
    public function testGetUid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setValue
     * @todo   Implement testSetValue().
     */
    public function testSetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setLn
     * @todo   Implement testSetLn().
     */
    public function testSetLn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getLn
     * @todo   Implement testGetLn().
     */
    public function testGetLn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setInd
     * @todo   Implement testSetInd().
     */
    public function testSetInd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getInd
     * @todo   Implement testGetInd().
     */
    public function testGetInd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setParent
     * @todo   Implement testSetParent().
     */
    public function testSetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::setChild
     * @todo   Implement testSetChild().
     */
    public function testSetChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::anyChildren
     * @todo   Implement testAnyChildren().
     */
    public function testAnyChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JNode::childrenCount
     * @todo   Implement testChildrenCount().
     */
    public function testChildrenCount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
