<?php

require_once '../JTreeRecursiveIterator.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 14:52:06.
 */
class JTreeRecursiveIteratorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var JTreeRecursiveIterator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new JTreeRecursiveIterator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers JTreeRecursiveIterator::endChildren
     * @todo   Implement testEndChildren().
     */
    public function testEndChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTreeRecursiveIterator::callHasChildren
     * @todo   Implement testCallHasChildren().
     */
    public function testCallHasChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTreeRecursiveIterator::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
