<?php

require_once '../JTree.php';
require_once '../JNode.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 12:16:23.
 */
class JTreeTest extends PHPUnit_Framework_TestCase {

    /**
     * @covers JTree::getTree
     */
    public function testGetTree() {
        $tree = new JTree();
        $this->assertTrue(count($tree->getTree()) == 1);
    }

    /**
     * @covers JTree::getNode
     * @expectedException Exception
     */
    public function testGetNodeNullArg() {
        $tree = new JTree();
        $tree->getNode();
    }
    
    /**
     * @covers JTree::getNode
     */
    public function testGetNodeInvalidUid() {
        $tree = new JTree();
        $this->assertFalse($tree->getNode('lalala'));
    }
    
    /**
     * @covers JTree::getNode
     */
    public function testGetNodeValidUid() {
        $tree = new JTree();
        $newNode = new JNode('test',1,1);
        $uid = $newNode->getUid();
        $tree->addFirst($uid);
        $this->assertEquals($uid, $tree->getHeadNode()->getChildren()[0]);
    }
    
    /**
     * @covers JTree::getHeadNode
     * @todo   Implement testGetHeadNode().
     */
    public function testGetHeadNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::setChild
     * @todo   Implement testSetChild().
     */
    public function testSetChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::setParent
     * @todo   Implement testSetParent().
     */
    public function testSetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::createNode
     * @todo   Implement testCreateNode().
     */
    public function testCreateNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::addChild
     * @todo   Implement testAddChild().
     */
    public function testAddChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::addFirst
     * @todo   Implement testAddFirst().
     */
    public function testAddFirst() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers JTree::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
