<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-07 at 12:32:35.
 */
class NodeValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var NodeValidator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NodeValidator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NodeValidator::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NodeValidator::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
