<?php

require_once '../NodeValidator.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 14:52:11.
 */
class NodeValidatorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var NodeValidator
     */
    //protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
//    protected function setUp() {
//        $this->object = new NodeValidator;
//    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
//    protected function tearDown() {
//        
//    }

    /**
     * @covers NodeValidator::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NodeValidator::validateAttributes
     * @todo   Implement testValidateAttributes().
     */
    public function testValidateAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NodeValidator::validateAttributeValue
     * @todo   Implement testValidateAttributeValue().
     */
    public function testValidateAttributeValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NodeValidator::validateRequiredAttributes
     * @todo   Implement testValidateRequiredAttributes().
     */
    public function testValidateRequiredAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NodeValidator::getMisspelledSuggestion
     * @todo   Implement testGetMisspelledSuggestion().
     */
    public function testGetMisspelledSuggestion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
