<?php

require_once '../Parser.php';
require_once 'HelperFunctions.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-07 at 12:32:16.
 */
class ParserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Parser
     */
    protected $object;
    protected $helper;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Parser('../tests/files/testMultiLineTag.html');
        $this->helper = new HelperFunctions();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Parser::runValidator
     * @todo   Implement testRunValidator().
     */
    public function testRunValidator() {
        //$this->object->parse();
        //$this->object->createParseTree();
        //$this->testRunValidator();
        //$this->expectOutputString('Success');
    }
    
    public function testRedirectToResults() {

    }
    
    public function testMergeLines() {
        $test = array ("a","b","c");
        $ret = $this->object->mergeLines($test, 0);
        $this->assertEquals("ab", $ret[0]);
        $this->assertEquals("|NULL|", $ret[1]);
        $this->assertEquals("c", $ret[2]);
    }
    
    public function testMergeLines2() {
        $test = array ("<html>","<head>","<title>","</title>", "</head>", "<body>","</body>","</html>");
        $expected = array("<html>","<head>","<title>","</title></head>", "|NULL|", "<body>","</body>","</html>");
        $ret = $this->object->mergeLines($test, 3);
        $this->assertTrue($this->helper->test_array_similarity($ret, $expected));
    }
    

    
    /**
     * @covers Parser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Parser::createParseTree
     * @todo   Implement testCreateParseTree().
     */
    public function testCreateParseTree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    


}
