<?php

require_once '../TagInfo.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-30 at 14:58:12.
 */
class TagInfoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TagInfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TagInfo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TagInfo::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::areGlobalAttributesSupported
     * @todo   Implement testAreGlobalAttributesSupported().
     */
    public function testAreGlobalAttributesSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::getRequiredAttributes
     * @todo   Implement testGetRequiredAttributes().
     */
    public function testGetRequiredAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::areEventAttributesSupported
     * @todo   Implement testAreEventAttributesSupported().
     */
    public function testAreEventAttributesSupported() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::isTagDeprecated
     * @todo   Implement testIsTagDeprecated().
     */
    public function testIsTagDeprecated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::getOptionalAttributes
     * @todo   Implement testGetOptionalAttributes().
     */
    public function testGetOptionalAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::getDeprecatedAttributes
     * @todo   Implement testGetDeprecatedAttributes().
     */
    public function testGetDeprecatedAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::getWithin
     * @todo   Implement testGetWithin().
     */
    public function testGetWithin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::requiresClosingTag
     * @todo   Implement testRequiresClosingTag().
     */
    public function testRequiresClosingTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TagInfo::isSelfClosing
     * @todo   Implement testIsSelfClosing().
     */
    public function testIsSelfClosing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
